//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenRW.Resources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class _internal {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal _internal() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OpenRW.Resources.internal", typeof(_internal).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die (.adf) Radio station audio file ähnelt.
        /// </summary>
        internal static string adf {
            get {
                return ResourceManager.GetString("adf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die (.cfg) Configuration file ähnelt.
        /// </summary>
        internal static string cfg {
            get {
                return ResourceManager.GetString("cfg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die (.col) Collision file ähnelt.
        /// </summary>
        internal static string col {
            get {
                return ResourceManager.GetString("col", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die (.dat) Data file ähnelt.
        /// </summary>
        internal static string dat {
            get {
                return ResourceManager.GetString("dat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die (.dff) Model file ähnelt.
        /// </summary>
        internal static string dff {
            get {
                return ResourceManager.GetString("dff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die (.gxt) Text file ähnelt.
        /// </summary>
        internal static string gxt {
            get {
                return ResourceManager.GetString("gxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die (.ide) Item definition file ähnelt.
        /// </summary>
        internal static string ide {
            get {
                return ResourceManager.GetString("ide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die (.ifp) Animation file ähnelt.
        /// </summary>
        internal static string ifp {
            get {
                return ResourceManager.GetString("ifp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die (.img) Archive file ähnelt.
        /// </summary>
        internal static string img {
            get {
                return ResourceManager.GetString("img", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die (.ipl) Item placement file ähnelt.
        /// </summary>
        internal static string ipl {
            get {
                return ResourceManager.GetString("ipl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string lblATR {
            get {
                return ResourceManager.GetString("lblATR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  not found ähnelt.
        /// </summary>
        internal static string noFiDES {
            get {
                return ResourceManager.GetString("noFiDES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The given folder does not contain the file  ähnelt.
        /// </summary>
        internal static string noFiTXT {
            get {
                return ResourceManager.GetString("noFiTXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Folder not found ähnelt.
        /// </summary>
        internal static string noFoDES {
            get {
                return ResourceManager.GetString("noFoDES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The given folder does not exist! ähnelt.
        /// </summary>
        internal static string noFoTXT {
            get {
                return ResourceManager.GetString("noFoTXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You&apos;re not connected to the internet! ähnelt.
        /// </summary>
        internal static string noInetACC {
            get {
                return ResourceManager.GetString("noInetACC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This IMG type is not supported yet. ähnelt.
        /// </summary>
        internal static string notFoundTWO {
            get {
                return ResourceManager.GetString("notFoundTWO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please select your ähnelt.
        /// </summary>
        internal static string pls1ST {
            get {
                return ResourceManager.GetString("pls1ST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  directory! ähnelt.
        /// </summary>
        internal static string plsLST {
            get {
                return ResourceManager.GetString("plsLST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die (.raw) SFX archive file ähnelt.
        /// </summary>
        internal static string raw {
            get {
                return ResourceManager.GetString("raw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die (.rep) Replay file ähnelt.
        /// </summary>
        internal static string rep {
            get {
                return ResourceManager.GetString("rep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die (.scm) Mission script file ähnelt.
        /// </summary>
        internal static string scm {
            get {
                return ResourceManager.GetString("scm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die (.sdt) SFX directory file ähnelt.
        /// </summary>
        internal static string sdt {
            get {
                return ResourceManager.GetString("sdt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die (.txd) Texture archive file ähnelt.
        /// </summary>
        internal static string txd {
            get {
                return ResourceManager.GetString("txd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unknown file ähnelt.
        /// </summary>
        internal static string unk {
            get {
                return ResourceManager.GetString("unk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Update available ähnelt.
        /// </summary>
        internal static string updAvaDES {
            get {
                return ResourceManager.GetString("updAvaDES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A new version of OpenRW is avilable. Download and install? The application will exit after the download finishes. ähnelt.
        /// </summary>
        internal static string updAvaTXT {
            get {
                return ResourceManager.GetString("updAvaTXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The update parameters seem to be broken. ähnelt.
        /// </summary>
        internal static string updBRK {
            get {
                return ResourceManager.GetString("updBRK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You already run the most current version. ähnelt.
        /// </summary>
        internal static string updNotNEC {
            get {
                return ResourceManager.GetString("updNotNEC", resourceCulture);
            }
        }
    }
}
